questions_paths:
- questions
file_name: quiz.pdf
output_directory: output/
submission_directory: submitted/
front_matter:
  title: Sample Quiz
  author: Claude Botson
  date: \today
  exam_information: This is a sample exam.
header:
  header_left: Some random text
  header_center: null
  header_right: Page \thepage \ of \ \pageref{LastPage}
  footer_left: null
  footer_center: null
  footer_right: null
